"""initial schema

Revision ID: 2a34f8914837
Revises:
Create Date: 2026-07-21 00:31:50.070146

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "2a34f8914837"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.Enum("creator", "participant", name="user_role"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "survey_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="template_status"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_survey_templates_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_templates")),
    )
    op.create_table(
        "survey_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "answer_type",
            sa.Enum(
                "single_select",
                "multi_select",
                "yes_no",
                "short_text",
                "long_text",
                "rating",
                "number",
                "date",
                name="answer_type",
            ),
            nullable=False,
        ),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allow_other", sa.Boolean(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("allow_follow_ups", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["survey_templates.id"],
            name=op.f("fk_survey_questions_template_id_survey_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_questions")),
        sa.UniqueConstraint("template_id", "position", name="question_template_position"),
    )
    op.create_table(
        "survey_template_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
            name=op.f("fk_survey_template_versions_published_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["survey_templates.id"],
            name=op.f("fk_survey_template_versions_template_id_survey_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_template_versions")),
        sa.UniqueConstraint("template_id", "version", name="version_template_version"),
    )
    op.create_table(
        "survey_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_version_id", sa.Uuid(), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("in_progress", "completed", "abandoned", name="run_status"),
            nullable=False,
        ),
        sa.Column("current_question_index", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["participant_id"], ["users.id"], name=op.f("fk_survey_runs_participant_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["survey_template_versions.id"],
            name=op.f("fk_survey_runs_template_version_id_survey_template_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_runs")),
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Enum("scripted", "follow_up", name="answer_kind"), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answered_by", sa.Uuid(), nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answered_by"], ["users.id"], name=op.f("fk_answers_answered_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["survey_runs.id"],
            name=op.f("fk_answers_run_id_survey_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answers")),
    )
    op.create_table(
        "run_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Enum("assistant", "user", name="message_role"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("answer_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["answers.id"], name=op.f("fk_run_messages_answer_id_answers")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["survey_runs.id"],
            name=op.f("fk_run_messages_run_id_survey_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_messages")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_messages")
    op.drop_table("answers")
    op.drop_table("survey_runs")
    op.drop_table("survey_template_versions")
    op.drop_table("survey_questions")
    op.drop_table("survey_templates")
    op.drop_table("users")
    # ### end Alembic commands ###
