"""add users.external_subject for sso

Revision ID: eee390652e33
Revises: b44c57e9a451
Create Date: 2026-07-31 03:25:27.204697

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "eee390652e33"
down_revision: str | None = "b44c57e9a451"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("external_subject", sa.String(length=255), nullable=True))
    op.create_unique_constraint(op.f("uq_users_external_subject"), "users", ["external_subject"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_external_subject"), "users", type_="unique")
    op.drop_column("users", "external_subject")
    # ### end Alembic commands ###
